---
# tasks file for mantisbt
- block:
    - name: Creating mandatory DB 
      include_role: 
        name: mysql
        tasks_from: db_remote
      vars:
        db_user: "{{ mantisbt_db_user }}"
        db_pass: "{{ mantisbt_db_pass }}"
        db_name: "{{ mantisbt_db_name }}"
    - name: Opening iptables if needed on remote mysql host
      include_role: 
        name: iptables
        tasks_from: remote-mysqld
  when: use_remote_mysql_host
  delegate_to: "{{ mysql_host }}"

- name: Configuring httpd
  include_role:
    name: httpd

- name: Configuring https
  include_role:
    name: httpd
    tasks_from: tls

- include_role:
    name: httpd
    tasks_from: scl-php

- include_role:
    name: postfix
    tasks_from: relay_to
  vars:
    postfix_relay_to: True 

- include_tasks: selinux.yml

- include_role:
    name: httpd
    tasks_from: pki-tls
  vars:
    pki_hostname: "{{ httpd_public_hostname }}"

- name: Distributing apache vhost files
  template:
    src: "{{ item }}.j2"
    dest: "/etc/httpd/conf.d/{{ item }}"
  with_items:
    - 10_bugs.conf
    - ssl-bugs.conf
  notify: restart_httpd  

# Backup
- name: Ensuring backup user and jobs
  include_role:
    name: centos-backup
    tasks_from: client

